"""Clusters PersonLoader's raw (given_name, surname) extractions across the
whole corpus into one entry per real person, merging OCR-spelling variants
of the same name (e.g. "ศิริพันธ์โนน" / "ศิริพันธ์" -- a dropped trailing
syllable; "ถิรายุ" / "ภิรายุ" -- a misread leading character).

Person names are open-vocabulary (see person_loader.py's module docstring),
so this isn't a hand-confirmed dictionary like faculties.json -- it's
generated by clustering raw mentions, then written out for a human sanity
pass over the merges before it's trusted. Two variants are considered the
same person if, based on the two OCR-defect shapes actually observed in
this corpus (tools/corpus_prep/tag_people.py's report):

1. Same given name, and one surname is a (length-bounded) prefix of the
   other -- a dropped trailing syllable -- OR the surnames are highly
   similar by edit distance (a mid-word misread character).
2. Same surname, and the given names are highly similar by edit distance
   with at most a 2-character length difference -- a misread character,
   not two different first names that happen to share syllables.

Deliberately does NOT merge on title: the same person's title can
legitimately change between meetings (a ผศ. promoted to รศ.) -- clustering
on the name only, and unioning across every co-occurring spelling via a
union-find, means a person who appears under 3+ spelling variants over the
years still collapses into one cluster even if not every pair of variants
is directly similar enough on its own (transitivity through a shared
variant).

Read-only with respect to the corpus. Writes:
- data/entity_dictionaries/people.json -- the canonical dictionary
- academic_resolutions/entity_tags/people_canonicalization_report.md --
  every cluster with >1 spelling merged, for a human to spot-check
  (gitignored, same as the rest of entity_tags/)

Run with:
    .venv/Scripts/python.exe tools/corpus_prep/canonicalize_people.py
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from difflib import SequenceMatcher
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CORPUS_ROOT = REPO / "academic_resolutions"
OUT_DICT_PATH = REPO / "data" / "entity_dictionaries" / "people.json"
OUT_REPORT_PATH = CORPUS_ROOT / "entity_tags" / "people_canonicalization_report.md"

# tools/corpus_prep is run directly (not via pytest's configured pythonpath),
# so src/ needs to be on sys.path explicitly to reuse the already-tested
# matcher instead of duplicating it here.
sys.path.insert(0, str(REPO / "src"))
from rag_lab.loaders.common import (  # noqa: E402
    iter_corpus_files,
    strip_document_header,
    strip_mapping_tables,
)
from rag_lab.loaders.person_loader import match_people  # noqa: E402

# A prefix-relation merge requires both surnames to already be at least this
# long (avoids trivial short-string false positives) AND the shorter one to
# retain at least this FRACTION of the longer one's length. A fixed absolute
# gap (e.g. "within 6 chars") was tried first and over-merged badly: common
# Thai surname-starting syllables like "ศิริ" are shared by many genuinely
# different surnames (ศิริพันธ์, ศิริพงศ์, ศิริวัฒน์, ...), and a short
# 4-char stub sits within 6 chars of all of them, silently bridging unrelated
# people together via union-find transitivity. A dropped trailing syllable
# is a small loss relative to the whole word (e.g. 9/12 chars retained,
# "ศิริพันธ์" from "ศิริพันธ์โนน"); a 4-char stub of a 12-char surname (33%
# retained) is not that -- it's a coincidence, not a truncation.
_MIN_PREFIX_LEN = 4
_MIN_PREFIX_RETENTION = 0.7

# Edit-distance thresholds for the non-prefix "misread character" case.
# Surnames get a slightly looser threshold than given names: they're longer
# on average in this corpus, so a single substitution moves the ratio less.
_SURNAME_SIMILARITY = 0.85
_GIVEN_SIMILARITY = 0.85
_MAX_GIVEN_LENGTH_GAP = 2


def collect_raw_counts(corpus_root: Path) -> Counter:
    """(title, given_name, surname) -> mention count, across every live
    (non-`.dup`) corpus file."""
    counts: Counter = Counter()
    for f in iter_corpus_files(corpus_root):
        try:
            text = f.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            text = f.read_text(encoding="utf-8-sig")
        text = strip_mapping_tables(strip_document_header(text))
        for p in match_people(text):
            counts[(p["title"], p["given_name"], p["surname"])] += 1
    return counts


def aggregate_by_name(raw_counts: Counter) -> tuple[dict, dict]:
    """Collapse title out of the identity key (a promotion shouldn't split
    a person into two clusters): (given, surname) -> total mention count,
    and (given, surname) -> Counter of the titles seen with that spelling
    (used only to pick a representative display title for the dictionary
    entry, never to affect clustering or to overwrite a per-mention title
    at match time)."""
    name_counts: dict[tuple[str, str], int] = {}
    title_counts: dict[tuple[str, str], Counter] = {}
    for (title, given, surname), n in raw_counts.items():
        key = (given, surname)
        name_counts[key] = name_counts.get(key, 0) + n
        title_counts.setdefault(key, Counter())[title] += n
    return name_counts, title_counts


def _prefix_related(a: str, b: str) -> bool:
    shorter, longer = (a, b) if len(a) <= len(b) else (b, a)
    if len(shorter) < _MIN_PREFIX_LEN:
        return False
    if len(shorter) / len(longer) < _MIN_PREFIX_RETENTION:
        return False
    return longer.startswith(shorter)


def _similar(a: str, b: str, threshold: float) -> bool:
    return SequenceMatcher(None, a, b).ratio() >= threshold


def _one_char_off(a: str, b: str) -> bool:
    """True if `a` and `b` are the same length and differ in at most one
    character position. A single misread character (the common OCR defect
    on given names, e.g. "ถิรายุ"/"ภิรายุ") only costs a SequenceMatcher
    ratio of (L-1)/L -- for the short given names typical in this corpus
    (4-6 chars) that lands well under a 0.85 ratio threshold, so this exact
    check is the primary safety net; _similar() with _GIVEN_SIMILARITY
    catches the remaining longer/different-length cases."""
    return len(a) == len(b) and sum(x != y for x, y in zip(a, b)) <= 1


class _UnionFind:
    def __init__(self, keys):
        self._parent = {k: k for k in keys}

    def find(self, k):
        root = k
        while self._parent[root] != root:
            root = self._parent[root]
        while self._parent[k] != root:
            self._parent[k], k = root, self._parent[k]
        return root

    def union(self, a, b) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self._parent[ra] = rb


def cluster_people(name_counts: dict, title_counts: dict) -> list[dict]:
    """Union-find clustering of (given, surname) keys into one entry per
    inferred real person. See module docstring for the two merge rules."""
    keys = list(name_counts)
    uf = _UnionFind(keys)

    by_given: dict[str, list[tuple[str, str]]] = {}
    by_surname: dict[str, list[tuple[str, str]]] = {}
    for given, surname in keys:
        by_given.setdefault(given, []).append((given, surname))
        by_surname.setdefault(surname, []).append((given, surname))

    for group in by_given.values():
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                s1, s2 = group[i][1], group[j][1]
                if _prefix_related(s1, s2) or _similar(s1, s2, _SURNAME_SIMILARITY):
                    uf.union(group[i], group[j])

    for group in by_surname.values():
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                g1, g2 = group[i][0], group[j][0]
                if abs(len(g1) - len(g2)) > _MAX_GIVEN_LENGTH_GAP:
                    continue
                if _one_char_off(g1, g2) or _similar(g1, g2, _GIVEN_SIMILARITY):
                    uf.union(group[i], group[j])

    clusters: dict[tuple[str, str], list[tuple[str, str]]] = {}
    for k in keys:
        clusters.setdefault(uf.find(k), []).append(k)

    entries = []
    for members in clusters.values():
        members_sorted = sorted(members, key=lambda k: -name_counts[k])
        canonical_given, canonical_surname = members_sorted[0]
        merged_titles: Counter = Counter()
        for m in members:
            merged_titles.update(title_counts[m])
        canonical_title = merged_titles.most_common(1)[0][0]
        aliases = [
            {"given": g, "surname": s, "count": name_counts[(g, s)]}
            for g, s in members_sorted[1:]
        ]
        entries.append(
            {
                "canonical_title": canonical_title,
                "canonical_given": canonical_given,
                "canonical_surname": canonical_surname,
                "canonical_full_name": f"{canonical_title}{canonical_given} {canonical_surname}",
                "count": sum(name_counts[m] for m in members),
                "aliases": aliases,
            }
        )
    entries.sort(key=lambda e: (-e["count"], e["canonical_full_name"]))
    return entries


def render_report(entries: list[dict]) -> str:
    merged = [e for e in entries if e["aliases"]]
    lines = [
        "# Person canonicalization report",
        "",
        f"- Total distinct-spelling raw mentions clustered: {sum(1 + len(e['aliases']) for e in entries)}",
        f"- Resulting person entries: {len(entries)}",
        f"- Entries with >=1 merged spelling variant: {len(merged)}",
        "",
        "## Merged clusters (spot-check these)",
        "",
    ]
    for e in merged:
        lines.append(f"{e['count']}\t{e['canonical_full_name']}")
        for a in sorted(e["aliases"], key=lambda a: -a["count"]):
            lines.append(f"\t  <- {a['given']} {a['surname']} ({a['count']})")
    return "\n".join(lines) + "\n"


def main() -> None:
    raw_counts = collect_raw_counts(CORPUS_ROOT)
    name_counts, title_counts = aggregate_by_name(raw_counts)
    entries = cluster_people(name_counts, title_counts)

    OUT_DICT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_DICT_PATH.write_text(
        json.dumps(entries, ensure_ascii=False, indent=1), encoding="utf-8"
    )
    OUT_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_REPORT_PATH.write_text(render_report(entries), encoding="utf-8")

    merged_count = sum(1 for e in entries if e["aliases"])
    print(f"[INFO] {len(name_counts)} distinct raw (given, surname) spellings")
    print(f"[INFO] clustered into {len(entries)} person entries")
    print(f"[INFO] {merged_count} entries merged >=1 spelling variant")
    print(f"[INFO] wrote {OUT_DICT_PATH}")
    print(f"[INFO] wrote {OUT_REPORT_PATH}")


if __name__ == "__main__":
    main()
